jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: channel:nixos-unstable
      - run: nix develop
      - run: echo pre-building
      - run: echo building
      - run: echo testing
      - run: echo deploying
"on": push
