jobs:
  ci-cd:
    runs-on: nixpkgs/nix-flakes
    steps:
      - uses: actions/checkout@v1
      - run: nix develop
      - run: echo pre-building
      - run: echo building
      - run: echo testing
      - run: echo deploying
"on": push
