jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          nix_path: channel:nixos-unstable
      - name: Pre Build
        run: nix develop --command menu
      - name: Build
        run: nix develop --command echo building
      - name: Test
        run: nix develop --command echo testing
      - name: Deploy
        run: nix develop --command echo deploying
"on": push
